VCSWP-15721: addition of active property to CallResult
FreeClimbAPI/ruby-sdk pull request #17
Opened 2021-10-29 23:05 UTC by kohearn-vail

…aught and addition of active property to CallResult

2021-11-02 21:40 UTC, ngarg-vail requested changes

2021-11-02 21:40 UTC, ngarg-vail commented on CHANGELOG.md
> +## [3.0.1] - 2021-1-29
Date is incorrect

2021-11-02 22:02 UTC, kohearn-vail commented on CHANGELOG.md
> +## [3.0.1] - 2021-1-29
This should be corrected now

2021-11-03 14:25 UTC, ngarg-vail approved these changes

2021-11-03 16:01 UTC, merged